name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.1

      - name: Install dependencies
        run: bun install

      - name: Bun Publish
        run: bun publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
